spring:
  application:
    name: learn-redis
  # 单机配置
  redis:
    host: localhost
    port: 6379

# redis 集群配置
#  redis:
#    cluster:
#      nodes: 172.16.0.3:6371,172.16.0.3:6372,172.16.0.3:6373,172.16.0.3:6374,172.16.0.3:6375,172.16.0.3:6376
#      max-redirects: 3
#    password: redispass
# redis 哨兵配置
#  redis:
#    sentinel:
#      master: mymaster
#      nodes: 192.168.1.6:26380,192.168.1.6:26381,192.168.1.6:26382
#    password: redispass
server:
  port: 8082
